title = 'this is the configuration file of the plugin XXX'

[CHEETAH3]

[CHEETAH3.connection]

serverurl = 'http://localhost:8080'

[CHEETAH3.folders]

bpc = '/home/adteurtrie/timepix/20231120 ASI Server 3.3.0 (TPX3)/examples/tpx3'
dacs = '/home/adteurtrie/timepix/20231120 ASI Server 3.3.0 (TPX3)/examples/tpx3'
data = '/home/adteurtrie/timepix/20231120 ASI Server 3.3.0 (TPX3)/examples/tpx3'